In [1]:
import pandas as pd
import numpy as np

# Import dataset

In [2]:
w19_hr = pd.read_csv('../data/2019/ugz_ogd_meteo_h1_2019.csv', header = 0)
w19_hr

,Datum,Standort,Parameter,Intervall,Einheit,Wert,Status
0,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,Hr,h1,%Hr,89.22,bereinigt
1,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,RainDur,h1,min,0.00,bereinigt
2,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,T,h1,°C,5.14,bereinigt
3,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,WD,h1,°,96.36,bereinigt
4,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,WVs,h1,m/s,0.49,bereinigt
...,...,...,...,...,...,...,...
183955,2019-12-31T23:00+0100,Zch_Stampfenbachstrasse,WD,h1,°,37.95,bereinigt
183956,2019-12-31T23:00+0100,Zch_Stampfenbachstrasse,WVs,h1,m/s,1.80,bereinigt
183957,2019-12-31T23:00+0100,Zch_Stampfenbachstrasse,WVv,h1,m/s,1.68,bereinigt
183958,2019-12-31T23:00+0100,Zch_Stampfenbachstrasse,p,h1,hPa,982.21,bereinigt
183959,2019-12-31T23:00+0100,Zch_Stampfenbachstrasse,StrGlo,h1,W/m2,0.02,bereinigt

In [3]:
w19_hr.head(50)

,Datum,Standort,Parameter,Intervall,Einheit,Wert,Status
0,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,Hr,h1,%Hr,89.22,bereinigt
1,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,RainDur,h1,min,0.00,bereinigt
2,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,T,h1,°C,5.14,bereinigt
3,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,WD,h1,°,96.36,bereinigt
4,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,WVs,h1,m/s,0.49,bereinigt
5,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,WVv,h1,m/s,0.38,bereinigt
6,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,p,h1,hPa,982.12,bereinigt
7,2019-01-01T00:00+0100,Zch_Schimmelstrasse,Hr,h1,%Hr,85.81,bereinigt
8,2019-01-01T00:00+0100,Zch_Schimmelstrasse,RainDur,h1,min,0.00,bereinigt
9,2019-01-01T00:00+0100,Zch_Schimmelstrasse,T,h1,°C,5.71,bereinigt
10,2019-01-01T00:00+0100,Zch_Schimmelstrasse,WD,h1,°,63.02,bereinigt
11,2019-01-01T00:00+0100,Zch_Schimmelstrasse,WVv,h1,m/s,0.26,bereinigt
12,2019-01-01T00:00+0100,Zch_Schimmelstrasse,p,h1,hPa,984.50,bereinigt
13,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,Hr,h1,%Hr,87.69,bereinigt
14,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,RainDur,h1,min,0.00,bereinigt
15,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,T,h1,°C,5.24,bereinigt
16,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,WD,h1,°,73.84,bereinigt
17,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,WVs,h1,m/s,1.19,bereinigt
18,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,WVv,h1,m/s,0.78,bereinigt
19,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,p,h1,hPa,981.72,bereinigt
20,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,StrGlo,h1,W/m2,0.02,bereinigt
21,2019-01-01T01:00+0100,Zch_Rosengartenstrasse,Hr,h1,%Hr,89.72,bereinigt
22,2019-01-01T01:00+0100,Zch_Rosengartenstrasse,RainDur,h1,min,0.00,bereinigt
23,2019-01-01T01:00+0100,Zch_Rosengartenstrasse,T,h1,°C,4.99,bereinigt
24,2019-01-01T01:00+0100,Zch_Rosengartenstrasse,WD,h1,°,98.64,bereinigt
25,2019-01-01T01:00+0100,Zch_Rosengartenstrasse,WVs,h1,m/s,0.33,bereinigt
26,2019-01-01T01:00+0100,Zch_Rosengartenstrasse,WVv,h1,m/s,0.28,bereinigt
27,2019-01-01T01:00+0100,Zch_Rosengartenstrasse,p,h1,hPa,982.20,bereinigt
28,2019-01-01T01:00+0100,Zch_Schimmelstrasse,Hr,h1,%Hr,85.58,bereinigt
29,2019-01-01T01:00+0100,Zch_Schimmelstrasse,RainDur,h1,min,0.00,bereinigt
30,2019-01-01T01:00+0100,Zch_Schimmelstrasse,T,h1,°C,5.50,bereinigt
31,2019-01-01T01:00+0100,Zch_Schimmelstrasse,WD,h1,°,36.66,bereinigt
32,2019-01-01T01:00+0100,Zch_Schimmelstrasse,WVv,h1,m/s,0.51,bereinigt
33,2019-01-01T01:00+0100,Zch_Schimmelstrasse,p,h1,hPa,984.64,bereinigt
34,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,Hr,h1,%Hr,87.71,bereinigt
35,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,RainDur,h1,min,0.00,bereinigt
36,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,T,h1,°C,5.09,bereinigt
37,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,WD,h1,°,120.15,bereinigt
38,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,WVs,h1,m/s,0.87,bereinigt
39,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,WVv,h1,m/s,0.50,bereinigt
40,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,p,h1,hPa,981.82,bereinigt
41,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,StrGlo,h1,W/m2,0.02,bereinigt
42,2019-01-01T02:00+0100,Zch_Rosengartenstrasse,Hr,h1,%Hr,89.72,bereinigt
43,2019-01-01T02:00+0100,Zch_Rosengartenstrasse,RainDur,h1,min,0.00,bereinigt
44,2019-01-01T02:00+0100,Zch_Rosengartenstrasse,T,h1,°C,5.07,bereinigt
45,2019-01-01T02:00+0100,Zch_Rosengartenstrasse,WD,h1,°,115.73,bereinigt
46,2019-01-01T02:00+0100,Zch_Rosengartenstrasse,WVs,h1,m/s,0.41,bereinigt
47,2019-01-01T02:00+0100,Zch_Rosengartenstrasse,WVv,h1,m/s,0.34,bereinigt
48,2019-01-01T02:00+0100,Zch_Rosengartenstrasse,p,h1,hPa,982.52,bereinigt
49,2019-01-01T02:00+0100,Zch_Schimmelstrasse,Hr,h1,%Hr,85.01,bereinigt

View datatypes

In [4]:
w19_hr.dtypes

Datum         object
Standort      object
Parameter     object
Intervall     object
Einheit       object
Wert         float64
Status        object
dtype: object

View locations

In [5]:
print(w19_hr['Standort'].unique())

['Zch_Rosengartenstrasse' 'Zch_Schimmelstrasse' 'Zch_Stampfenbachstrasse']

View parameters

In [6]:
print(w19_hr['Parameter'].unique())

['Hr' 'RainDur' 'T' 'WD' 'WVs' 'WVv' 'p' 'StrGlo']

# Filter  parameters

In [8]:
conditions = ['StrGlo', 'WD', 'WVv']
filtered = w19_hr.loc[~w19_hr['Parameter'].isin(conditions)]

In [9]:
filtered.head(50)

,Datum,Standort,Parameter,Intervall,Einheit,Wert,Status
0,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,Hr,h1,%Hr,89.22,bereinigt
1,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,RainDur,h1,min,0.00,bereinigt
2,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,T,h1,°C,5.14,bereinigt
4,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,WVs,h1,m/s,0.49,bereinigt
6,2019-01-01T00:00+0100,Zch_Rosengartenstrasse,p,h1,hPa,982.12,bereinigt
7,2019-01-01T00:00+0100,Zch_Schimmelstrasse,Hr,h1,%Hr,85.81,bereinigt
8,2019-01-01T00:00+0100,Zch_Schimmelstrasse,RainDur,h1,min,0.00,bereinigt
9,2019-01-01T00:00+0100,Zch_Schimmelstrasse,T,h1,°C,5.71,bereinigt
12,2019-01-01T00:00+0100,Zch_Schimmelstrasse,p,h1,hPa,984.50,bereinigt
13,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,Hr,h1,%Hr,87.69,bereinigt
14,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,RainDur,h1,min,0.00,bereinigt
15,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,T,h1,°C,5.24,bereinigt
17,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,WVs,h1,m/s,1.19,bereinigt
19,2019-01-01T00:00+0100,Zch_Stampfenbachstrasse,p,h1,hPa,981.72,bereinigt
21,2019-01-01T01:00+0100,Zch_Rosengartenstrasse,Hr,h1,%Hr,89.72,bereinigt
22,2019-01-01T01:00+0100,Zch_Rosengartenstrasse,RainDur,h1,min,0.00,bereinigt
23,2019-01-01T01:00+0100,Zch_Rosengartenstrasse,T,h1,°C,4.99,bereinigt
25,2019-01-01T01:00+0100,Zch_Rosengartenstrasse,WVs,h1,m/s,0.33,bereinigt
27,2019-01-01T01:00+0100,Zch_Rosengartenstrasse,p,h1,hPa,982.20,bereinigt
28,2019-01-01T01:00+0100,Zch_Schimmelstrasse,Hr,h1,%Hr,85.58,bereinigt
29,2019-01-01T01:00+0100,Zch_Schimmelstrasse,RainDur,h1,min,0.00,bereinigt
30,2019-01-01T01:00+0100,Zch_Schimmelstrasse,T,h1,°C,5.50,bereinigt
33,2019-01-01T01:00+0100,Zch_Schimmelstrasse,p,h1,hPa,984.64,bereinigt
34,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,Hr,h1,%Hr,87.71,bereinigt
35,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,RainDur,h1,min,0.00,bereinigt
36,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,T,h1,°C,5.09,bereinigt
38,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,WVs,h1,m/s,0.87,bereinigt
40,2019-01-01T01:00+0100,Zch_Stampfenbachstrasse,p,h1,hPa,981.82,bereinigt
42,2019-01-01T02:00+0100,Zch_Rosengartenstrasse,Hr,h1,%Hr,89.72,bereinigt
43,2019-01-01T02:00+0100,Zch_Rosengartenstrasse,RainDur,h1,min,0.00,bereinigt
44,2019-01-01T02:00+0100,Zch_Rosengartenstrasse,T,h1,°C,5.07,bereinigt
46,2019-01-01T02:00+0100,Zch_Rosengartenstrasse,WVs,h1,m/s,0.41,bereinigt
48,2019-01-01T02:00+0100,Zch_Rosengartenstrasse,p,h1,hPa,982.52,bereinigt
49,2019-01-01T02:00+0100,Zch_Schimmelstrasse,Hr,h1,%Hr,85.01,bereinigt
50,2019-01-01T02:00+0100,Zch_Schimmelstrasse,RainDur,h1,min,0.00,bereinigt
51,2019-01-01T02:00+0100,Zch_Schimmelstrasse,T,h1,°C,5.51,bereinigt
54,2019-01-01T02:00+0100,Zch_Schimmelstrasse,p,h1,hPa,984.92,bereinigt
55,2019-01-01T02:00+0100,Zch_Stampfenbachstrasse,Hr,h1,%Hr,87.14,bereinigt
56,2019-01-01T02:00+0100,Zch_Stampfenbachstrasse,RainDur,h1,min,0.00,bereinigt
57,2019-01-01T02:00+0100,Zch_Stampfenbachstrasse,T,h1,°C,5.16,bereinigt
59,2019-01-01T02:00+0100,Zch_Stampfenbachstrasse,WVs,h1,m/s,1.22,bereinigt
61,2019-01-01T02:00+0100,Zch_Stampfenbachstrasse,p,h1,hPa,982.10,bereinigt
63,2019-01-01T03:00+0100,Zch_Rosengartenstrasse,Hr,h1,%Hr,89.45,bereinigt
64,2019-01-01T03:00+0100,Zch_Rosengartenstrasse,RainDur,h1,min,0.00,bereinigt
65,2019-01-01T03:00+0100,Zch_Rosengartenstrasse,T,h1,°C,4.69,bereinigt
67,2019-01-01T03:00+0100,Zch_Rosengartenstrasse,WVs,h1,m/s,0.62,bereinigt
69,2019-01-01T03:00+0100,Zch_Rosengartenstrasse,p,h1,hPa,982.24,bereinigt
70,2019-01-01T03:00+0100,Zch_Schimmelstrasse,Hr,h1,%Hr,84.78,bereinigt
71,2019-01-01T03:00+0100,Zch_Schimmelstrasse,RainDur,h1,min,0.00,bereinigt
72,2019-01-01T03:00+0100,Zch_Schimmelstrasse,T,h1,°C,5.39,bereinigt

# Create new dataframe with locations sorted under timepoints

In [84]:
w19_new = pd.pivot(filtered, index = ['Datum', 'Standort'], columns = ['Parameter'], values = ['Wert'])

In [85]:
w19_new

                                                Wert                      \
Parameter                                         Hr RainDur     T   WVs
Datum                 Standort
2019-01-01T00:00+0100 Zch_Rosengartenstrasse   89.22     0.0  5.14  0.49
                      Zch_Schimmelstrasse      85.81     0.0  5.71   NaN
                      Zch_Stampfenbachstrasse  87.69     0.0  5.24  1.19
2019-01-01T01:00+0100 Zch_Rosengartenstrasse   89.72     0.0  4.99  0.33
                      Zch_Schimmelstrasse      85.58     0.0  5.50   NaN
...                                              ...     ...   ...   ...
2019-12-31T22:00+0100 Zch_Schimmelstrasse      90.16     0.0  0.87   NaN
                      Zch_Stampfenbachstrasse  93.05     0.0  0.18  2.76
2019-12-31T23:00+0100 Zch_Rosengartenstrasse   93.93     0.0 -0.65  0.58
                      Zch_Schimmelstrasse      90.24     0.0  0.09   NaN
                      Zch_Stampfenbachstrasse  91.33     0.0 -0.26  1.80


Parameter                                           p
Datum                 Standort
2019-01-01T00:00+0100 Zch_Rosengartenstrasse   982.12
                      Zch_Schimmelstrasse      984.50
                      Zch_Stampfenbachstrasse  981.72
2019-01-01T01:00+0100 Zch_Rosengartenstrasse   982.20
                      Zch_Schimmelstrasse      984.64
...                                               ...
2019-12-31T22:00+0100 Zch_Schimmelstrasse      985.07
                      Zch_Stampfenbachstrasse  982.18
2019-12-31T23:00+0100 Zch_Rosengartenstrasse   982.78
                      Zch_Schimmelstrasse      985.05
                      Zch_Stampfenbachstrasse  982.21

[26280 rows x 5 columns]

In [86]:
w19_new.columns.levels

FrozenList([['Wert'], ['Hr', 'RainDur', 'T', 'WVs', 'p']])

In [87]:
w19_new.columns.get_level_values(1)

Index(['Hr', 'RainDur', 'T', 'WVs', 'p'], dtype='object', name='Parameter')

In [88]:
w19_new.columns = w19_new.columns.droplevel()

In [89]:
w19_new.head(50)

Parameter                                         Hr  RainDur     T   WVs  \
Datum                 Standort
2019-01-01T00:00+0100 Zch_Rosengartenstrasse   89.22     0.00  5.14  0.49
                      Zch_Schimmelstrasse      85.81     0.00  5.71   NaN
                      Zch_Stampfenbachstrasse  87.69     0.00  5.24  1.19
2019-01-01T01:00+0100 Zch_Rosengartenstrasse   89.72     0.00  4.99  0.33
                      Zch_Schimmelstrasse      85.58     0.00  5.50   NaN
                      Zch_Stampfenbachstrasse  87.71     0.00  5.09  0.87
2019-01-01T02:00+0100 Zch_Rosengartenstrasse   89.72     0.00  5.07  0.41
                      Zch_Schimmelstrasse      85.01     0.00  5.51   NaN
                      Zch_Stampfenbachstrasse  87.14     0.00  5.16  1.22
2019-01-01T03:00+0100 Zch_Rosengartenstrasse   89.45     0.00  4.69  0.62
                      Zch_Schimmelstrasse      84.78     0.00  5.39   NaN
                      Zch_Stampfenbachstrasse  87.22     0.00  4.86  1.26
2019-01-01T04:00+0100 Zch_Rosengartenstrasse   87.97     0.00  4.69  0.34
                      Zch_Schimmelstrasse      84.73     0.00  5.23   NaN
                      Zch_Stampfenbachstrasse  85.84     0.00  4.80  1.29
2019-01-01T05:00+0100 Zch_Rosengartenstrasse   86.92     0.00  4.80  0.29
                      Zch_Schimmelstrasse      84.52     0.00  5.08   NaN
                      Zch_Stampfenbachstrasse  84.78     0.00  4.88  1.01
2019-01-01T06:00+0100 Zch_Rosengartenstrasse   86.66     0.00  4.58  0.28
                      Zch_Schimmelstrasse      83.44     0.00  4.97   NaN
                      Zch_Stampfenbachstrasse  85.58     0.00  4.78  0.97
2019-01-01T07:00+0100 Zch_Rosengartenstrasse   85.23     0.00  4.60  0.43
                      Zch_Schimmelstrasse      82.90     0.00  4.97   NaN
                      Zch_Stampfenbachstrasse  84.80     0.00  4.68  0.94
2019-01-01T08:00+0100 Zch_Rosengartenstrasse   86.44     0.00  4.41  0.61
                      Zch_Schimmelstrasse      84.64     0.00  4.67   NaN
                      Zch_Stampfenbachstrasse  85.10     0.00  4.59  1.40
2019-01-01T09:00+0100 Zch_Rosengartenstrasse   86.76     0.00  4.40  0.42
                      Zch_Schimmelstrasse      83.93     0.00  4.89   NaN
                      Zch_Stampfenbachstrasse  85.65     0.00  4.45  0.92
2019-01-01T10:00+0100 Zch_Rosengartenstrasse   84.97     0.00  4.86  0.77
                      Zch_Schimmelstrasse      82.32     0.00  5.26   NaN
                      Zch_Stampfenbachstrasse  83.94     0.00  4.80  1.58
2019-01-01T11:00+0100 Zch_Rosengartenstrasse   82.57     0.00  4.98  0.94
                      Zch_Schimmelstrasse      80.57     0.00  5.39   NaN
                      Zch_Stampfenbachstrasse  81.43     0.00  5.12  2.34
2019-01-01T12:00+0100 Zch_Rosengartenstrasse   82.79     0.00  4.87  0.95
                      Zch_Schimmelstrasse      79.98     0.00  5.37   NaN
                      Zch_Stampfenbachstrasse  81.36     0.00  5.01  2.49
2019-01-01T13:00+0100 Zch_Rosengartenstrasse   80.53     0.00  5.33  1.08
                      Zch_Schimmelstrasse      77.32     0.00  5.68   NaN
                      Zch_Stampfenbachstrasse  78.63     0.00  5.41  2.52
2019-01-01T14:00+0100 Zch_Rosengartenstrasse   81.34     0.00  5.56  0.67
                      Zch_Schimmelstrasse      77.00     0.00  6.12   NaN
                      Zch_Stampfenbachstrasse  78.84     0.00  5.70  2.04
2019-01-01T15:00+0100 Zch_Rosengartenstrasse   80.96     0.00  5.43  0.79
                      Zch_Schimmelstrasse      78.97     0.00  5.73   NaN
                      Zch_Stampfenbachstrasse  79.15     0.00  5.55  1.80
2019-01-01T16:00+0100 Zch_Rosengartenstrasse   80.17     0.02  5.38  0.64
                      Zch_Schimmelstrasse      76.68     0.00  5.77   NaN

Parameter                                           p
Datum                 Standort
2019-01-01T00:00+0100 Zch_Rosengartenstrasse   982.12
                      Zch_Schimmelstrasse      984.50
                      Zch_Stampfenbachstrasse  981.72
2019-01-01T01:00+0100 Zch_Rosengartenstrasse   982.20
                      Zch_Schimmelstrasse      984.64
                      Zch_Stampfenbachstrasse  981.82
2019-01-01T02:00+0100 Zch_Rosengartenstrasse   982.52
                      Zch_Schimmelstrasse      984.92
                      Zch_Stampfenbachstrasse  982.10
2019-01-01T03:00+0100 Zch_Rosengartenstrasse   982.24
                      Zch_Schimmelstrasse      984.68
                      Zch_Stampfenbachstrasse  981.86
2019-01-01T04:00+0100 Zch_Rosengartenstrasse   981.28
                      Zch_Schimmelstrasse      983.69
                      Zch_Stampfenbachstrasse  980.81
2019-01-01T05:00+0100 Zch_Rosengartenstrasse   980.76
                      Zch_Schimmelstrasse      983.17
                      Zch_Stampfenbachstrasse  980.26
2019-01-01T06:00+0100 Zch_Rosengartenstrasse   980.54
                      Zch_Schimmelstrasse      982.94
                      Zch_Stampfenbachstrasse  980.04
2019-01-01T07:00+0100 Zch_Rosengartenstrasse   980.42
                      Zch_Schimmelstrasse      982.86
                      Zch_Stampfenbachstrasse  979.94
2019-01-01T08:00+0100 Zch_Rosengartenstrasse   980.63
                      Zch_Schimmelstrasse      983.07
                      Zch_Stampfenbachstrasse  980.12
2019-01-01T09:00+0100 Zch_Rosengartenstrasse   980.52
                      Zch_Schimmelstrasse      982.95
                      Zch_Stampfenbachstrasse  980.05
2019-01-01T10:00+0100 Zch_Rosengartenstrasse   980.46
                      Zch_Schimmelstrasse      982.89
                      Zch_Stampfenbachstrasse  980.00
2019-01-01T11:00+0100 Zch_Rosengartenstrasse   980.37
                      Zch_Schimmelstrasse      982.81
                      Zch_Stampfenbachstrasse  979.90
2019-01-01T12:00+0100 Zch_Rosengartenstrasse   979.78
                      Zch_Schimmelstrasse      982.22
                      Zch_Stampfenbachstrasse  979.38
2019-01-01T13:00+0100 Zch_Rosengartenstrasse   979.19
                      Zch_Schimmelstrasse      981.69
                      Zch_Stampfenbachstrasse  978.79
2019-01-01T14:00+0100 Zch_Rosengartenstrasse   979.34
                      Zch_Schimmelstrasse      981.77
                      Zch_Stampfenbachstrasse  978.91
2019-01-01T15:00+0100 Zch_Rosengartenstrasse   979.52
                      Zch_Schimmelstrasse      981.97
                      Zch_Stampfenbachstrasse  979.12
2019-01-01T16:00+0100 Zch_Rosengartenstrasse   979.66
                      Zch_Schimmelstrasse      982.09

# Averaged values under each timepoint

Save dates

In [91]:
dates = w19_new.reset_index(inplace=False)
dates = dates['Datum']
dates = dates.drop_duplicates()
dates = dates.to_frame()
dates = dates.reset_index(drop = True)
dates.head(50)

                    Datum
0   2019-01-01T00:00+0100
1   2019-01-01T01:00+0100
2   2019-01-01T02:00+0100
3   2019-01-01T03:00+0100
4   2019-01-01T04:00+0100
5   2019-01-01T05:00+0100
6   2019-01-01T06:00+0100
7   2019-01-01T07:00+0100
8   2019-01-01T08:00+0100
9   2019-01-01T09:00+0100
10  2019-01-01T10:00+0100
11  2019-01-01T11:00+0100
12  2019-01-01T12:00+0100
13  2019-01-01T13:00+0100
14  2019-01-01T14:00+0100
15  2019-01-01T15:00+0100
16  2019-01-01T16:00+0100
17  2019-01-01T17:00+0100
18  2019-01-01T18:00+0100
19  2019-01-01T19:00+0100
20  2019-01-01T20:00+0100
21  2019-01-01T21:00+0100
22  2019-01-01T22:00+0100
23  2019-01-01T23:00+0100
24  2019-01-02T00:00+0100
25  2019-01-02T01:00+0100
26  2019-01-02T02:00+0100
27  2019-01-02T03:00+0100
28  2019-01-02T04:00+0100
29  2019-01-02T05:00+0100
30  2019-01-02T06:00+0100
31  2019-01-02T07:00+0100
32  2019-01-02T08:00+0100
33  2019-01-02T09:00+0100
34  2019-01-02T10:00+0100
35  2019-01-02T11:00+0100
36  2019-01-02T12:00+0100
37  2019-01-02T13:00+0100
38  2019-01-02T14:00+0100
39  2019-01-02T15:00+0100
40  2019-01-02T16:00+0100
41  2019-01-02T17:00+0100
42  2019-01-02T18:00+0100
43  2019-01-02T19:00+0100
44  2019-01-02T20:00+0100
45  2019-01-02T21:00+0100
46  2019-01-02T22:00+0100
47  2019-01-02T23:00+0100
48  2019-01-03T00:00+0100
49  2019-01-03T01:00+0100

Average values

In [39]:
w19_new.groupby(np.arange(len(w19_new))//3).mean()

Parameter         Hr  RainDur         T    WVs           p
0          87.573333      0.0  5.363333  0.840  982.780000
1          87.670000      0.0  5.193333  0.600  982.886667
2          87.290000      0.0  5.246667  0.815  983.180000
3          87.150000      0.0  4.980000  0.940  982.926667
4          86.180000      0.0  4.906667  0.815  981.926667
...              ...      ...       ...    ...         ...
8755       89.503333      0.0  1.636667  0.850  982.966667
8756       91.496667      0.0  1.246667  1.065  983.070000
8757       92.470000      0.0  0.900000  1.600  983.140000
8758       92.656667      0.0  0.333333  1.825  983.350000
8759       91.833333      0.0 -0.273333  1.190  983.346667

[8760 rows x 5 columns]

Join dataframes

In [92]:
w19_new = w19_new.reset_index(drop=True)
dates = dates.reset_index(drop=True)

In [94]:
dates.head(50)

                    Datum
0   2019-01-01T00:00+0100
1   2019-01-01T01:00+0100
2   2019-01-01T02:00+0100
3   2019-01-01T03:00+0100
4   2019-01-01T04:00+0100
5   2019-01-01T05:00+0100
6   2019-01-01T06:00+0100
7   2019-01-01T07:00+0100
8   2019-01-01T08:00+0100
9   2019-01-01T09:00+0100
10  2019-01-01T10:00+0100
11  2019-01-01T11:00+0100
12  2019-01-01T12:00+0100
13  2019-01-01T13:00+0100
14  2019-01-01T14:00+0100
15  2019-01-01T15:00+0100
16  2019-01-01T16:00+0100
17  2019-01-01T17:00+0100
18  2019-01-01T18:00+0100
19  2019-01-01T19:00+0100
20  2019-01-01T20:00+0100
21  2019-01-01T21:00+0100
22  2019-01-01T22:00+0100
23  2019-01-01T23:00+0100
24  2019-01-02T00:00+0100
25  2019-01-02T01:00+0100
26  2019-01-02T02:00+0100
27  2019-01-02T03:00+0100
28  2019-01-02T04:00+0100
29  2019-01-02T05:00+0100
30  2019-01-02T06:00+0100
31  2019-01-02T07:00+0100
32  2019-01-02T08:00+0100
33  2019-01-02T09:00+0100
34  2019-01-02T10:00+0100
35  2019-01-02T11:00+0100
36  2019-01-02T12:00+0100
37  2019-01-02T13:00+0100
38  2019-01-02T14:00+0100
39  2019-01-02T15:00+0100
40  2019-01-02T16:00+0100
41  2019-01-02T17:00+0100
42  2019-01-02T18:00+0100
43  2019-01-02T19:00+0100
44  2019-01-02T20:00+0100
45  2019-01-02T21:00+0100
46  2019-01-02T22:00+0100
47  2019-01-02T23:00+0100
48  2019-01-03T00:00+0100
49  2019-01-03T01:00+0100

In [99]:
w19 = pd.merge(w19_new, dates, left_index = True, right_index = True)
w19 = w19[['Datum', 'Hr', 'RainDur', 'T', 'WVs', 'p']]

In [100]:
w19.head(50)

                    Datum     Hr  RainDur     T   WVs       p
0   2019-01-01T00:00+0100  89.22     0.00  5.14  0.49  982.12
1   2019-01-01T01:00+0100  85.81     0.00  5.71   NaN  984.50
2   2019-01-01T02:00+0100  87.69     0.00  5.24  1.19  981.72
3   2019-01-01T03:00+0100  89.72     0.00  4.99  0.33  982.20
4   2019-01-01T04:00+0100  85.58     0.00  5.50   NaN  984.64
5   2019-01-01T05:00+0100  87.71     0.00  5.09  0.87  981.82
6   2019-01-01T06:00+0100  89.72     0.00  5.07  0.41  982.52
7   2019-01-01T07:00+0100  85.01     0.00  5.51   NaN  984.92
8   2019-01-01T08:00+0100  87.14     0.00  5.16  1.22  982.10
9   2019-01-01T09:00+0100  89.45     0.00  4.69  0.62  982.24
10  2019-01-01T10:00+0100  84.78     0.00  5.39   NaN  984.68
11  2019-01-01T11:00+0100  87.22     0.00  4.86  1.26  981.86
12  2019-01-01T12:00+0100  87.97     0.00  4.69  0.34  981.28
13  2019-01-01T13:00+0100  84.73     0.00  5.23   NaN  983.69
14  2019-01-01T14:00+0100  85.84     0.00  4.80  1.29  980.81
15  2019-01-01T15:00+0100  86.92     0.00  4.80  0.29  980.76
16  2019-01-01T16:00+0100  84.52     0.00  5.08   NaN  983.17
17  2019-01-01T17:00+0100  84.78     0.00  4.88  1.01  980.26
18  2019-01-01T18:00+0100  86.66     0.00  4.58  0.28  980.54
19  2019-01-01T19:00+0100  83.44     0.00  4.97   NaN  982.94
20  2019-01-01T20:00+0100  85.58     0.00  4.78  0.97  980.04
21  2019-01-01T21:00+0100  85.23     0.00  4.60  0.43  980.42
22  2019-01-01T22:00+0100  82.90     0.00  4.97   NaN  982.86
23  2019-01-01T23:00+0100  84.80     0.00  4.68  0.94  979.94
24  2019-01-02T00:00+0100  86.44     0.00  4.41  0.61  980.63
25  2019-01-02T01:00+0100  84.64     0.00  4.67   NaN  983.07
26  2019-01-02T02:00+0100  85.10     0.00  4.59  1.40  980.12
27  2019-01-02T03:00+0100  86.76     0.00  4.40  0.42  980.52
28  2019-01-02T04:00+0100  83.93     0.00  4.89   NaN  982.95
29  2019-01-02T05:00+0100  85.65     0.00  4.45  0.92  980.05
30  2019-01-02T06:00+0100  84.97     0.00  4.86  0.77  980.46
31  2019-01-02T07:00+0100  82.32     0.00  5.26   NaN  982.89
32  2019-01-02T08:00+0100  83.94     0.00  4.80  1.58  980.00
33  2019-01-02T09:00+0100  82.57     0.00  4.98  0.94  980.37
34  2019-01-02T10:00+0100  80.57     0.00  5.39   NaN  982.81
35  2019-01-02T11:00+0100  81.43     0.00  5.12  2.34  979.90
36  2019-01-02T12:00+0100  82.79     0.00  4.87  0.95  979.78
37  2019-01-02T13:00+0100  79.98     0.00  5.37   NaN  982.22
38  2019-01-02T14:00+0100  81.36     0.00  5.01  2.49  979.38
39  2019-01-02T15:00+0100  80.53     0.00  5.33  1.08  979.19
40  2019-01-02T16:00+0100  77.32     0.00  5.68   NaN  981.69
41  2019-01-02T17:00+0100  78.63     0.00  5.41  2.52  978.79
42  2019-01-02T18:00+0100  81.34     0.00  5.56  0.67  979.34
43  2019-01-02T19:00+0100  77.00     0.00  6.12   NaN  981.77
44  2019-01-02T20:00+0100  78.84     0.00  5.70  2.04  978.91
45  2019-01-02T21:00+0100  80.96     0.00  5.43  0.79  979.52
46  2019-01-02T22:00+0100  78.97     0.00  5.73   NaN  981.97
47  2019-01-02T23:00+0100  79.15     0.00  5.55  1.80  979.12
48  2019-01-03T00:00+0100  80.17     0.02  5.38  0.64  979.66
49  2019-01-03T01:00+0100  76.68     0.00  5.77   NaN  982.09